pipeline {
  agent any

  tools {
    maven 'jenkin-mvn'
  }  
 
  stages {
  
	    
   stage('Initialize') {
      steps {
        echo "PATH = ${PATH}"
        echo "M2_HOME = ${M2_HOME}"
      }
    }
    
    stage ('Build') {
            steps {
                sh 'mvn clean package -Dmaven.test.skip=true' 
            }
            post {
                success {
                    echo "aravind"
                }
            }
        }
    
    
  } 
	  
}