pipeline {
  agent any

  tools {
    maven 'jenkin-mvn'
  }

  stages {
    stage('Cloning Git') {
	      steps {
	        git([url: 'https://github.com/aravindcodehub/elocator.git', branch: 'master', credentialsId: 'd2703892-e658-4ac1-a465-880ca87fcf60'])
	      }
	    }
	    
    stage('Build') {
      steps {
        sh 'mvn clean package -Dmaven.test.skip=true'
      }
    }
    
   
  } 
	  
}